on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}"
      - name: Print a message
        run: echo "This is a message from my GitHub Actions job!"
      - name: Show runner OS
        run: echo "Running on ${{ runner.os }}"
      - name: Display repository details
        run: echo "Repository ${{ github.repository }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t reboot-bot:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Manual approve
      run: echo "Repository ${{ github.repository }}"