on:
  push:
    branches:
      - master

jobs:

  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run unit tests
        run: python -m unittest tests/tests.py

  linter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install flake8
      - name: Run Flake8
        run: flake8 ./src --max-line-length=120

  build:
    runs-on: self-hosted
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
          # This command is just an example to show your secret being printed
          # Ensure you remove any print statements of your secrets. GitHub does
          # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: ip_list.py

      - name: Build Docker image
        run: docker build -t remote-bot:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Remove old container
        run: docker rm -f remote-bot

      - uses: actions/checkout@v4
      - name: Run a command inside the container
        run: docker run -d --name remote-bot remote-bot:latest